name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os-type }}

    strategy:
      matrix:
        os-type: [ windows-2022, macos-13 ]
        ac-version: [ 28 ]

    steps:
      - uses: actions/checkout@v3

      - name: Checkout the submodule
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Setup Xcode
        if: runner.os == 'macOS'
        run: |
          if [ ${{ matrix.ac-version }} -lt 29 ]
          then
            xcVersion=14.2
          else
            xcVersion=15.2
          fi
          echo Xcode version: $xcVersion
          sudo xcode-select -s /Applications/Xcode_$xcVersion.app

      - name: Run build script
        run: |
          python Tools/BuildAddOn.py --configFile config.json --acVersion ${{ matrix.ac-version }} --package
